meta_product_name: "Mister Cocktail"
meta_title: "Renaud's Cocktail"
meta_description: "A place where you can create your own cocktail and find some inspiration"
meta_image: "cocktails.jpg"
meta_url: "renaudscocktails.herokuapp.com"
